"""report.py - builds the downloadable progress report (a PDF) with reportlab."""
import io
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def _safe(text) -> str:
    """The built-in PDF fonts only know Western characters; swap others for '?'."""
    cleaned = str(text).encode("latin-1", "replace").decode("latin-1")
    return escape(cleaned)


def build_progress_pdf(display_name, goal_title, level, points, streak, tasks, series, today) -> bytes:
    """tasks = list of {"description","is_done"}; series = list of (date, logged 0/1, percent)."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, leftMargin=2 * cm, rightMargin=2 * cm,
                            topMargin=2 * cm, bottomMargin=2 * cm, title="Aura progress report")
    styles = getSampleStyleSheet()
    story = [
        Paragraph("Aura Progress Report", styles["Title"]),
        Paragraph(f"{_safe(display_name)} - generated {today.isoformat()}", styles["Normal"]),
        Spacer(1, 14),
    ]
    summary = [["Current goal", _safe(goal_title) or "-"], ["Level", _safe(level)],
               ["Aura points", str(points)], ["Current streak (days)", str(streak)]]
    table = Table([[Paragraph(str(c), styles["Normal"]) for c in row] for row in summary],
                  colWidths=[5 * cm, 11 * cm])
    table.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                               ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke)]))
    story += [table, Spacer(1, 14), Paragraph("Tasks", styles["Heading2"])]
    if tasks:
        for t in tasks:
            mark = "[x]" if t["is_done"] else "[ ]"
            story.append(Paragraph(f"{mark} {_safe(t['description'])}", styles["Normal"]))
    else:
        story.append(Paragraph("No tasks yet.", styles["Normal"]))
    story += [Spacer(1, 14), Paragraph("Last 14 days", styles["Heading2"])]
    rows = [["Date", "Logged", "7-day consistency"]]
    for d, logged, pct in series[-14:]:
        rows.append([d.isoformat(), "Yes" if logged else "-", f"{pct}%"])
    day_table = Table(rows, colWidths=[5 * cm, 4 * cm, 6 * cm])
    day_table.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                                   ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey)]))
    story += [day_table, Spacer(1, 14),
              Paragraph("Generated by Aura. AI-made plans can contain mistakes; verify important facts.",
                        styles["Italic"])]
    doc.build(story)
    return buffer.getvalue()
